version: '3'

services:
  server:
    container_name: hoa-admin
    image: nginx:1.21.6
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #    ports:
    #      - 8080:80
    labels:
      - traefik.enable=true
      - traefik.http.services.hoa-admin.loadbalancer.server.port=80
      - traefik.http.routers.hoa-admin.rule=Host("admin.hoa.innque.com")
      - traefik.http.routers.hoa-admin.entrypoints=web
      - traefik.http.routers.hoa-admin_secured.rule=Host("admin.hoa.innque.com")
      - traefik.http.routers.hoa-admin_secured.entrypoints=websecure
      - traefik.http.routers.hoa-admin_secured.tls.certresolver=myhttpchallenge
      - traefik.http.routers.hoa-admin.middlewares=redirect@file


networks:
  default:
    external:
      name: proxy-server-network
